spring:
  application:
    name: auth-demo-app
  datasource:
    url: jdbc:postgresql://localhost/auth_db
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
app:
  jwtSecret: yourfavoritecolor
  jwtExpiration: 3600
server:
  error:
    include-message: always
    include-stacktrace: never
